export {
  setBridge,
  hasBridge,
  subscribeBridgeChanges,
  type IpcBridge,
  type Unlisten,
} from '../ipc/bridge'
export { call, callBinary } from '../ipc/invoke'
export { type PluginSubscription } from '../ipc/plugin'
export {
  actionPerformed,
  actionsReady,
  cancelRecording,
  deleteStaged,
  listStaged,
  readStaged,
  recordingStatus,
  startRecording,
  stopRecording,
  subscribeRecordingLevel,
  subscribeRecordingNativeAction,
  subscribeRecordingStopped,
  type RecordingLevelEvent,
  type RecordingNativeActionEvent,
  type RecordingStatus,
  type RecordingStopResponse,
  type RecordingStoppedEvent,
  type StagedRecordingFile,
  type StartRecordingOptions,
} from '../ipc/recording-plugin'
export { impactLight } from '../ipc/keyboard-plugin'
export {
  getAppVersion,
  getAppPlatform,
  isMobilePlatform,
  mobileStorage,
  mobileStorageLocal,
  icloudDownloadPending,
  icloudPendingCount,
  icloudRequestDownloads,
  icloudStatus,
  icloudAdoptGraph,
  icloudConflictsScan,
  icloudWatchStart,
  icloudWatchStop,
  type AppPlatform,
  type IcloudDownloadScope,
  type IcloudScanOptions,
  type IcloudSweepScope,
  type IcloudStatus,
  type IcloudSweepOutcome,
  type MobileStorageInfo,
  type MobileStorageKind,
} from '../ipc/commands'
export { confirmQuit, subscribeQuitRequested } from '../app/quit'
export {
  beginBackgroundTask,
  endBackgroundTask,
  type BackgroundTaskToken,
} from '../app/background-task'
export { WINDOW_NAVIGATE_EVENT, subscribeWindowNavigate } from '../app/window-events'
export { toggleDevtools } from '../app/devtools'
export {
  agentSkillStatus,
  agentSkillInstall,
  agentSkillUninstall,
  type AgentSkillInstallState,
  type AgentSkillStatus,
} from '../app/agent-skill'
export { chunkNote, type NoteChunk } from '../embeddings/chunk'
export {
  embedStatus,
  embedEnsure,
  embedTexts,
  embedApply,
  embedRemove,
  subscribeEmbedStatus,
  embedStatusSchema,
  type EmbedStatus,
  type EmbedProgress,
  type EmbedChunkPayload,
} from '../embeddings/commands'
export { embedNote, backfillEmbeddings } from '../embeddings/pipeline'
export {
  retrieve,
  relatedNotes,
  fuseRanked,
  type RetrievalHit,
  type RetrieveOptions,
} from '../embeddings/retrieve'
export {
  appErrorSchema,
  errorMessage,
  isAppError,
  toAppError,
  ReflectError,
  type AppError,
} from '../errors'
export {
  DAILY_DIR,
  NOTES_DIR,
  TEMPLATES_DIR,
  ASSETS_DIR,
  AUDIO_MEMOS_DIR,
  dailyPath,
  notePath,
  templatePath,
  assetPath,
  audioMemoPath,
  descriptionPathFor,
  DESCRIPTION_SUFFIX,
  isDaily,
  isNotePath,
  isAttachmentPath,
  isSafeVisibleGraphPath,
  classifyGraphPath,
  mayContainNotes,
  isTemplatePath,
  dateFromDailyPath,
  noteFileStem,
  foldGraphPath,
  isCalendarDate,
  type GraphPathKind,
} from '../graph/paths'
export {
  wikiNoteReference,
  markdownNoteReference,
  noteBasenameKey,
  type NoteReference,
} from '../graph/note-reference'
export {
  isValidReflectNoteId,
  isReflectManagedNotePath,
  isReflectManagedNote,
} from '../graph/note-management'
export {
  graphInfoSchema,
  recentGraphSchema,
  fileMetaSchema,
  noteCreateOutcomeSchema,
  graphImportProgressSchema,
  graphImportSummarySchema,
  windowBootstrapSchema,
  type GraphInfo,
  type RecentGraph,
  type FileMeta,
  type NoteCreateOutcome,
  type GraphImportProgress,
  type GraphImportSummary,
  type WindowBootstrap,
} from '../graph/schemas'
export {
  openGraph,
  openNoteWindow,
  openBrowserWindow,
  showQuickCapture,
  hideQuickCapture,
  windowBootstrap,
  closeNoteWindows,
  createGraph,
  importReflectV1Zip,
  subscribeImportProgress,
  cancelReflectV1Import,
  markReflectV1ImportOwnWrites,
  exportWrite,
  hapticFeedback,
  type HapticPattern,
  readNote,
  readNoteLocal,
  type LocalNoteRead,
  writeNote,
  createNoteIfAbsent,
  writeAsset,
  readAsset,
  openAsset,
  revealAsset,
  listDir,
  noteExists,
  deleteNote,
  deleteAudioMemo,
  listFiles,
  listAttachments,
  vaultScanStats,
  type VaultScanStats,
  recentGraphs,
  forgetRecent,
  deleteGraph,
  captureHostRegister,
  captureInboxList,
  captureInboxRead,
  captureInboxSpool,
  captureInboxReject,
  captureInboxRemove,
  captureMetaFetch,
  captureSharedInboxRelay,
  promoteCaptureScreenshot,
} from '../graph/commands'
export { createAsset, importAsset } from '../graph/assets'
export { assetFileName } from '../graph/asset-names'
export {
  newNoteId,
  newNoteSource,
  untitledNoteSeed,
  untitledNotePath,
  isUntitledNotePath,
  createNoteWithTitle,
  resolveOrCreateNoteWithTitle,
  type ResolveOrCreateNoteResult,
} from '../graph/create-note'
export {
  resolveExistingMarkdownTarget,
  resolveExistingWikiTarget,
  type ExistingWikiTargetResolution,
} from '../graph/resolve-existing-wiki-target'
export {
  settingsSchema,
  editorMarkdownSyntaxSchema,
  editorSpellCheckSchema,
  editorDefaultBulletSchema,
  editorBulletAfterHeadingSchema,
  editorSmoothCaretAnimationSchema,
  editorTextSizeSchema,
  editorFullWidthSchema,
  editorFontFamilySchema,
  editorLineSpacingSchema,
  sidebarWidthSchema,
  contextSidebarWidthSchema,
  SIDEBAR_WIDTH_RANGE,
  CONTEXT_SIDEBAR_WIDTH_RANGE,
  clampSidebarWidth,
  semanticSearchEnabledSchema,
  describeAssetsSchema,
  transcriptionFormatSchema,
  contactsEnabledSchema,
  THEME_PREFERENCE_IDS,
  themePreferenceSchema,
  DARK_THEME_IDS,
  accentColorSchema,
  ACCENT_COLOR_IDS,
  ACCENT_SWATCH_HEX,
  customAccentColorSchema,
  DEFAULT_CUSTOM_ACCENT,
  glassIntensitySchema,
  GLASS_INTENSITY_IDS,
  uiRadiusSchema,
  uiDensitySchema,
  UI_DENSITY_IDS,
  DENSITY_ROW_HEIGHT,
  UI_RADIUS_IDS,
  uiTextSizeSchema,
  UI_TEXT_SIZE_IDS,
  chatTextSizeSchema,
  CHAT_TEXT_SIZE_IDS,
  EDITOR_TEXT_SIZE_IDS,
  timeFormatSchema,
  dateFormatSchema,
  weekStartDaySchema,
  browserSearchEngineSchema,
  browserOpenLinksInAppSchema,
  weekStartDow,
  allNotesFilterTagsSchema,
  savedSearchSchema,
  savedSearchesSchema,
  taskFiltersSchema,
  calendarEnabledSchema,
  calendarIdsSchema,
  graphColorSchema,
  graphColorsSchema,
  GRAPH_COLOR_IDS,
  aiProviderIdSchema,
  openAiCompatibleBaseUrlSchema,
  aiProviderConfigSchema,
  aiProvidersSchema,
  defaultAiProviderIdSchema,
  chatModelSelectionSchema,
  chatSystemPromptSchema,
  CHAT_SYSTEM_PROMPT_MAX_LENGTH,
  normalizeChatSystemPrompt,
  aiPromptModeSchema,
  aiPromptSchema,
  aiPromptsSchema,
  DEFAULT_SETTINGS,
  type Settings,
  type EditorMarkdownSyntax,
  type EditorTextSize,
  type EditorFontFamily,
  type EditorLineSpacing,
  type SidebarWidthRange,
  type ThemePreference,
  type AccentColor,
  type GlassIntensity,
  type UiRadius,
  type UiDensity,
  type UiTextSize,
  type ChatTextSize,
  type TimeFormat,
  type DateFormat,
  type WeekStartDay,
  type BrowserSearchEngine,
  type AllNotesFilterTags,
  type AllNotesView,
  collectionViewForAllNotesView,
  type SavedCollectionView,
  type OpenNoteTab,
  type SavedSearch,
  type TaskFilters,
  type CalendarIds,
  type GraphColor,
  type GraphColors,
  type AiProviderId,
  type HostedAiProviderId,
  type AiProviderConfig,
  type HostedAiProviderConfig,
  type OpenAiCompatibleProviderConfig,
  type ClaudeCliProviderConfig,
  type CodexCliProviderConfig,
  type AiPrompt,
  type AiPromptMode,
} from '../settings/schema'
export { loadSettings, saveSettings } from '../settings/commands'
export {
  contactsAuthorizationSchema,
  contactMatchSchema,
  contactsAuthorizationStatus,
  requestContactsAccess,
  lookupContactsByEmail,
  lookupContactsByName,
  isContactsReadable,
  type ContactsAuthorization,
  type ContactMatch,
} from '../contacts/commands'
export {
  contactLinkSuggestions,
  contactNamesEqual,
  matchContactForTitle,
  suggestContactForTitle,
} from '../contacts/match'
export {
  contactDetailsMarkdown,
  appendContactDetails,
  noteHasContactDetails,
} from '../contacts/markdown'
export { pickContactForEmail, resolveAttendeeContact } from '../contacts/resolve'
export {
  ensurePersonNote,
  resolvePerson,
  resolvePersonContact,
  type BlockedPersonResolution,
  type BlockedPersonContactResolution,
  type EnsurePersonNoteInput,
  type EnsurePersonNoteResult,
  type ExistingPersonResolution,
  type ExistingPersonContactResolution,
  type MissingPersonResolution,
  type NewPersonContactResolution,
  type PersonContactResolution,
  type PersonResolution,
} from '../contacts/person'
export {
  ptyOpen,
  ptyWrite,
  ptyAck,
  ptyResize,
  ptyClose,
  subscribePtyData,
  subscribePtyExit,
  type PtyOpenResult,
  type PtyDataEvent,
  type PtyExitEvent,
} from '../pty/commands'
export {
  browserEmbedShow,
  browserEmbedBounds,
  browserEmbedClose,
  browserEmbedNavigate,
  browserEmbedBack,
  browserEmbedForward,
  browserEmbedReload,
  browserEmbedOpen,
  browserEmbedRead,
  subscribeBrowserNavigated,
  type BrowserEmbedRect,
  type BrowserNavigatedEvent,
  type BrowserPageRead,
} from '../browser/commands'
export {
  IAP_PRODUCT_IDS,
  iapGetProducts,
  iapPurchase,
  iapRestorePurchases,
  iapIsOwned,
  subscribeIapPurchaseUpdated,
  type IapProduct,
} from '../ipc/iap-plugin'
