import { useState, type ReactElement, type ReactNode } from 'react'
import { isDaily } from '@reflect/core'
import {
  ExternalLink,
  FileDown,
  FolderOpen,
  Link2,
  Lock,
  LockOpen,
  Pin,
  PinOff,
  Trash2,
} from 'lucide-react'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuTrigger,
} from '@/components/ui/context-menu'
import { keybindingFor } from '@/lib/commands/app-commands'
import { formatBindingLabel } from '@/lib/keybindings'
import { useNoteRow } from '@/hooks/use-note-row'
import { usePinnedNotes } from '@/hooks/use-pinned-notes'
import { runCopyNotePath } from '@/lib/note-copy-path'
import { runCopyDeepLink } from '@/lib/note-deep-link'
import { runNoteExport } from '@/lib/note-export'
import { toggleNotePinned } from '@/lib/note-pin'
import { toggleNotePrivate } from '@/lib/note-private'
import { startOperation } from '@/lib/operations'
import { openRouteInNewWindow } from '@/lib/windows/open-in-new-window'
import { useGraph } from '@/providers/graph-provider'
import { NoteTrashDialog } from '@/components/notes/note-trash-dialog'

/** The attribute a row or card carries so the list's menu knows its note. */
export const NOTE_PATH_ATTRIBUTE = 'data-note-path'

interface NoteListContextMenuProps {
  /** The list whose rows/cards carry {@link NOTE_PATH_ATTRIBUTE}. */
  children: ReactNode
}

/** A command's binding as the menu's trailing hint, or nothing when unbound. */
function Hint({ command }: { command: string }): ReactElement | null {
  const binding = keybindingFor(command)
  return binding === null ? null : (
    <ContextMenuShortcut>{formatBindingLabel(binding)}</ContextMenuShortcut>
  )
}

/**
 * The right-click menu for a note, wherever notes are listed.
 *
 * One menu per **list**, not per row, and that is a performance decision as
 * much as a structural one: Base UI's context-menu trigger installs a
 * document-level `contextmenu` listener and a full floating-menu root, and
 * the menu's own state hooks (`useNoteRow` opens a per-path index query)
 * would otherwise run once per visible row — a few hundred listeners and
 * point queries on a long All Notes grid, all for menus that are closed.
 * Here a capture-phase handler on the list resolves which row was clicked
 * from its {@link NOTE_PATH_ATTRIBUTE}, and a single menu instance queries
 * only that note, only while the menu exists.
 *
 * Every entry already existed as a command or a context-sidebar button — the
 * menu adds no capability, it puts the capabilities where the hand already
 * is. The keyboard hints are read from the command definitions rather than
 * written out, so the menu teaches the shortcuts and cannot drift from the
 * real bindings.
 */
export function NoteListContextMenu({ children }: NoteListContextMenuProps): ReactElement {
  const [path, setPath] = useState<string | null>(null)

  return (
    <ContextMenu>
      <ContextMenuTrigger render={<div className="contents" />}>
        <div
          className="contents"
          onContextMenuCapture={(event) => {
            const row = (event.target as Element).closest?.(`[${CSS.escape(NOTE_PATH_ATTRIBUTE)}]`)
            const next = row?.getAttribute(NOTE_PATH_ATTRIBUTE) ?? null
            if (next === null) {
              // Not over a note: swallow the event before Base UI's trigger
              // sees it, so the menu can never open on a stale path.
              event.stopPropagation()
              return
            }
            setPath(next)
          }}
        >
          {children}
        </div>
      </ContextMenuTrigger>
      {path === null ? null : <NoteContextMenuItems path={path} />}
    </ContextMenu>
  )
}

/**
 * The menu itself, mounted only once a row has been right-clicked — which is
 * what keeps its queries (pin state, the note's `private` flag) scoped to the
 * one note under the pointer instead of every note on screen.
 *
 * Daily notes are a deliberate exception on one entry: they are generated by
 * date and the app recreates them, so trashing one is offered nowhere (the
 * delete helper refuses it too — this is the UI-layer half of that pair).
 */
function NoteContextMenuItems({ path }: { path: string }): ReactElement {
  const { graph } = useGraph()
  const isPinned = usePinnedNotes().some((note) => note.path === path)
  const isPrivate = useNoteRow(path)?.isPrivate ?? false
  const [confirmingTrash, setConfirmingTrash] = useState(false)

  // Every action needs the generation the note was indexed under; without an
  // open graph the menu still renders (so the gesture is never dead) and each
  // action reports through the operations toast instead of failing silently.
  const generation = graph?.generation
  const withGeneration = (label: string, run: (generation: number) => Promise<void>) => () => {
    if (generation === undefined) {
      startOperation(label).fail('No graph is open.')
      return
    }
    void run(generation)
  }

  return (
    <>
      <ContextMenuContent>
        <ContextMenuItem
          onClick={() => {
            void openRouteInNewWindow({ kind: 'note', path })
          }}
        >
          <ExternalLink aria-hidden />
          Open in new window
          <Hint command="note.openInNewWindow" />
        </ContextMenuItem>

        <ContextMenuSeparator />

        <ContextMenuItem
          onClick={withGeneration('Updating pin', async (at) => {
            await toggleNotePinned(path, at)
          })}
        >
          {isPinned ? <PinOff aria-hidden /> : <Pin aria-hidden />}
          {isPinned ? 'Un-pin' : 'Pin'}
          <Hint command="note.togglePin" />
        </ContextMenuItem>
        <ContextMenuItem
          onClick={withGeneration('Updating privacy', async (at) => {
            await toggleNotePrivate(path, at)
          })}
        >
          {isPrivate ? <LockOpen aria-hidden /> : <Lock aria-hidden />}
          {isPrivate ? 'Unlock note' : 'Lock note'}
          <Hint command="note.togglePrivate" />
        </ContextMenuItem>

        <ContextMenuSeparator />

        <ContextMenuItem
          onClick={withGeneration('Copying deep link', async (at) => {
            await runCopyDeepLink(path, at)
          })}
        >
          <Link2 aria-hidden />
          Copy deep link
          <Hint command="note.copyDeepLink" />
        </ContextMenuItem>
        <ContextMenuItem
          onClick={() => {
            void runCopyNotePath(graph?.root ?? null, path)
          }}
        >
          <FolderOpen aria-hidden />
          Copy note path
          <Hint command="note.copyPath" />
        </ContextMenuItem>
        <ContextMenuItem
          onClick={withGeneration('Exporting note', async (at) => {
            await runNoteExport(path, at)
          })}
        >
          <FileDown aria-hidden />
          Export as HTML…
        </ContextMenuItem>

        {isDaily(path) ? null : (
          <>
            <ContextMenuSeparator />
            <ContextMenuItem
              variant="destructive"
              onClick={() => {
                setConfirmingTrash(true)
              }}
            >
              <Trash2 aria-hidden />
              Move to Trash
            </ContextMenuItem>
          </>
        )}
      </ContextMenuContent>

      {/* The same confirm the bulk action uses, over a one-note selection:
          one delete path, one dialog, one set of failure semantics. */}
      <NoteTrashDialog
        open={confirmingTrash}
        onOpenChange={setConfirmingTrash}
        paths={[path]}
        onTrashed={() => {
          setConfirmingTrash(false)
        }}
      />
    </>
  )
}
