import { useState, type ReactElement, type ReactNode } from 'react'
import { isDaily } from '@reflect/core'
import {
  ExternalLink,
  FolderOpen,
  Link,
  Lock,
  LockOpen,
  NoteDownload,
  Pin,
  PinOff,
  Trash,
} from '@/components/icons'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuTrigger,
} from '@/components/ui/context-menu'
import { keybindingFor } from '@/lib/commands/app-commands'
import { formatBindingLabel } from '@/lib/keybindings'
import { useNoteRow } from '@/hooks/use-note-row'
import { usePinnedNotes } from '@/hooks/use-pinned-notes'
import { runCopyNotePath } from '@/lib/note-copy-path'
import { runCopyDeepLink } from '@/lib/note-deep-link'
import { runNoteExport } from '@/lib/note-export'
import { toggleNotePinned } from '@/lib/note-pin'
import { toggleNotePrivate } from '@/lib/note-private'
import { startOperation } from '@/lib/operations'
import { openRouteInNewWindow } from '@/lib/windows/open-in-new-window'
import { useGraph } from '@/providers/graph-provider'
import { AllNotesTrashDialog } from '@/components/all-notes/all-notes-trash-dialog'

interface NoteContextMenuProps {
  /** Graph-relative path of the note the menu acts on. */
  path: string
  /** The element that answers the right-click — a row, a card, a tab. */
  children: ReactNode
}

/** A command's binding as one display label, or null when it has none. */
function hintFor(commandId: string): string | null {
  const binding = keybindingFor(commandId)
  return binding === null ? null : formatBindingLabel(binding)
}

const HINTS = {
  newWindow: hintFor('note.openInNewWindow'),
  pin: hintFor('note.togglePin'),
  private: hintFor('note.togglePrivate'),
  deepLink: hintFor('note.copyDeepLink'),
  path: hintFor('note.copyPath'),
}

/**
 * The right-click menu for a note, wherever a note is listed: All Notes rows
 * and cards, the sidebar, the tab strip.
 *
 * Every entry here already existed as a command or a context-sidebar button —
 * this adds no capability, it puts the capabilities where the hand already is.
 * That is also why the keyboard hints are read from the command definitions
 * rather than written out: the menu teaches the shortcuts instead of competing
 * with them, and it cannot drift from the real bindings.
 *
 * Daily notes are a deliberate exception on one entry: they are generated by
 * date and the app recreates them, so trashing one is offered nowhere (the
 * delete helper refuses it too — this is the UI-layer half of that pair).
 */
export function NoteContextMenu({ path, children }: NoteContextMenuProps): ReactElement {
  const { graph } = useGraph()
  const isPinned = usePinnedNotes().some((note) => note.path === path)
  const isPrivate = useNoteRow(path)?.isPrivate ?? false
  const [confirmingTrash, setConfirmingTrash] = useState(false)

  // Every action needs the generation the note was indexed under; without an
  // open graph the menu still renders (so the gesture is never dead) and each
  // action reports through the operations toast instead of failing silently.
  const generation = graph?.generation
  const withGeneration = (label: string, run: (generation: number) => Promise<void>) => () => {
    if (generation === undefined) {
      startOperation(label).fail('No graph is open.')
      return
    }
    void run(generation)
  }

  return (
    <>
      <ContextMenu>
        <ContextMenuTrigger render={<div className="contents" />}>{children}</ContextMenuTrigger>
        <ContextMenuContent>
          <ContextMenuItem
            onClick={() => {
              void openRouteInNewWindow({ kind: 'note', path })
            }}
          >
            <ExternalLink aria-hidden />
            Open in new window
            {HINTS.newWindow === null ? null : (
              <ContextMenuShortcut>{HINTS.newWindow}</ContextMenuShortcut>
            )}
          </ContextMenuItem>

          <ContextMenuSeparator />

          <ContextMenuItem
            onClick={withGeneration('Updating pin', async (at) => {
              await toggleNotePinned(path, at)
            })}
          >
            {isPinned ? <PinOff aria-hidden /> : <Pin aria-hidden />}
            {isPinned ? 'Un-pin' : 'Pin'}
            {HINTS.pin === null ? null : <ContextMenuShortcut>{HINTS.pin}</ContextMenuShortcut>}
          </ContextMenuItem>
          <ContextMenuItem
            onClick={withGeneration('Updating privacy', async (at) => {
              await toggleNotePrivate(path, at)
            })}
          >
            {isPrivate ? <LockOpen aria-hidden /> : <Lock aria-hidden />}
            {isPrivate ? 'Unlock note' : 'Lock note'}
            {HINTS.private === null ? null : (
              <ContextMenuShortcut>{HINTS.private}</ContextMenuShortcut>
            )}
          </ContextMenuItem>

          <ContextMenuSeparator />

          <ContextMenuItem
            onClick={withGeneration('Copying deep link', async (at) => {
              await runCopyDeepLink(path, at)
            })}
          >
            <Link aria-hidden />
            Copy deep link
            {HINTS.deepLink === null ? null : (
              <ContextMenuShortcut>{HINTS.deepLink}</ContextMenuShortcut>
            )}
          </ContextMenuItem>
          <ContextMenuItem
            onClick={() => {
              void runCopyNotePath(graph?.root ?? null, path)
            }}
          >
            <FolderOpen aria-hidden />
            Copy note path
            {HINTS.path === null ? null : <ContextMenuShortcut>{HINTS.path}</ContextMenuShortcut>}
          </ContextMenuItem>
          <ContextMenuItem
            onClick={withGeneration('Exporting note', async (at) => {
              await runNoteExport(path, at)
            })}
          >
            <NoteDownload aria-hidden />
            Export as HTML…
          </ContextMenuItem>

          {isDaily(path) ? null : (
            <>
              <ContextMenuSeparator />
              <ContextMenuItem
                variant="destructive"
                onClick={() => {
                  setConfirmingTrash(true)
                }}
              >
                <Trash aria-hidden />
                Move to Trash
              </ContextMenuItem>
            </>
          )}
        </ContextMenuContent>
      </ContextMenu>

      {/* The same confirm the bulk action uses, over a one-note selection:
          one delete path, one dialog, one set of failure semantics. */}
      <AllNotesTrashDialog
        open={confirmingTrash}
        onOpenChange={setConfirmingTrash}
        paths={[path]}
        onTrashed={() => {
          setConfirmingTrash(false)
        }}
      />
    </>
  )
}
