export {
  TAG_TYPE_MARKER,
  RESERVED_FRONTMATTER_KEYS,
  tagPropertyTypeSchema,
  tagPropertySchema,
  isPropertyKey,
  propertyKeyForName,
  parseTagTypeFrontmatter,
  encodeTagTypeJson,
  decodeTagTypeJson,
  tagNameForDefinitionPath,
  tagDefinitionPath,
  isTagDefinitionNote,
  relationValue,
  relationDisplay,
  relationTarget,
  type TagProperty,
  type TagPropertyType,
  type TagType,
} from './tag-type'
export {
  extractNoteProperties,
  type IndexedProperty,
  type IndexedPropertyValueType,
} from './properties'
